### ISSUE TITLE
In general confusion.

### ISSUE THREAD

**Issue by swiedaa1** [launchscout/nku#19]
I am a bit turned around with what exactly we should be doing. I had all of my pages working just fine with the updated post controller, html pages, etc. Well, I started trying to add in the code from the slides for the user_controller, etc but now I am curious as to if I am over complicating things.
I am currently receiving a NameError and thats fine. I'm not worried abotu that. Thats simply because I started trying to add in the user controller/method/etc. 
Current problems broken down: 
- Should we have a post controller AND a user controller?
- I cant for the life of me figure out how to reroute my submit form to the home page. I'm not sure if the submit page I have is acceptable. It shows all of the updated/submitted information and informs the student that everything has been submitted successfully. Then I have a "home page" link where it brings you to the list (one extra step than the directions call for)
-  I havent even begun the Gravatar portion since I havent pade it that far. Suggestions help.
- Will the teacher need their own page? Like, Do they have to sign in to Bueller to see the student information or should they see the same home page the students see? 

Rails repo: https://github.com/swiedaa1/nku-rails

**Comment by alexkoepke** [comment]
You are not allone!!! I have started the rails for zombies, http://railsforzombies.org/, so I would suggest trying that.—
Alex Koepke
(513) 236-7281

**Comment by rockwood** [comment]
This assignment doesn't need to interact with the blog you created for the last assignment. Basically your blog will still live under the url `/posts` and the new students app will live under something like `/students` (or `/users` if you prefer)

I would recommend running through the [getting-up-and-running](http://guides.rubyonrails.org/getting_started.html#getting-up-and-running) section of the Getting Started Guide and anywhere "Posts" is mentioned, replace it with "Users". Users will have different attributes than posts (`email` instead of `title` for instance), but the model, controller, and views should be pretty much identical.

**Comment by swiedaa1** [comment]
I've been working on redoing this. I swear I've redone it 6 times now. Should I be replacing `@posts` with `@users`?

**Comment by swiedaa1** [comment]
Same with `posts_path`, should that become `users_path`?

**Comment by rockwood** [comment]
Yep. You should end up with with Models, Views and Controllers for both users and posts.
