### ISSUE TITLE
Tutorial 5.2: The First Form

### ISSUE THREAD

**Issue by MatthewMcElwain** [launchscout/nku#4]
The form works up until I add "url: posts_path" to new.html.erb, then I get this error
![capture](https://f.cloud.github.com/assets/6433263/1959449/d2cc0aac-822e-11e3-9962-728219a87cfe.JPG)
I may have rooted my program to the wrong location in routes.rb, I have it pointing to "root 'posts#new'"

**Comment by jaimerump** [comment]
I remember getting this same error, but in my case it was because I had the colon on the front of posts_path instead of the end of url. You have the syntax right, so that shouldn't be the problem. I don't think the root should be the problem, since that's just the default route, the route it goes with when you don't have any extra parameters on the end of the url. It couldn't hurt to try to fix that though. If you can still access the output from the rake routes command, that might reveal something enlightening.

**Comment by rockwood** [comment]
Do you have the line `resources :posts` in your routes.rb file?

**Comment by MatthewMcElwain** [comment]
I added "resources :posts" to my program and it works now, thanks for the help.
