### ISSUE TITLE
Active record database queries

### ISSUE THREAD

**Issue by camdixon** [launchscout/nku#71]
I have created attendances on various dates for my main account "test@gmail.com" by using the rails console.  Kevin mentioned there is a bug in the absent function in class to where a student will not show as absent when they have no attendances ever (meaning it can't join with the attendance and student table because it's not an outer join).

Regardless when I run this command in the console I get accounts to show up multiple times under absent instead of just once.  Below you can even see it references the same student's ID multiple times.  How to fix this?

`absent = Student.absent(Date.today)`

`Student Load (0.3ms)  SELECT "students".* FROM "students" INNER JOIN "attendances" ON "attendances"."student_id" = "students"."id" WHERE ("attendances"."attended_on" != '2014-02-22')          
 => #<ActiveRecord::Relation [#<Student id: 4, name: "Test", nickname: "Test", email: "test@gmail.com", image_url: "", password_digest: "$2a$10$Ezc7Ncysvk17BoH.v/aOs.3Jmcu1ZdWVd0GnKQZiE/cy...">,
 #<Student id: 4, name: "Test", nickname: "Test", email: "test@gmail.com", image_url: "", password_digest: "$2a$10$Ezc7Ncysvk17BoH.v/aOs.3Jmcu1ZdWVd0GnKQZiE/cy...">, #<Student id: 4, name: "Test
", nickname: "Test", email: "test@gmail.com", image_url: "", password_digest: "$2a$10$Ezc7Ncysvk17BoH.v/aOs.3Jmcu1ZdWVd0GnKQZiE/cy...">, #<Student id: 4, name: "Test", nickname: "Test", email: "
test@gmail.com", image_url: "", password_digest: "$2a$10$Ezc7Ncysvk17BoH.v/aOs.3Jmcu1ZdWVd0GnKQZiE/cy...">, #<Student id: 4, name: "Test", nickname: "Test", email: "test@gmail.com", image_url: "
", password_digest: "$2a$10$Ezc7Ncysvk17BoH.v/aOs.3Jmcu1ZdWVd0GnKQZiE/cy...">, #<Student id: 4, name: "Test", nickname: "Test", email: "test@gmail.com", image_url: "", password_digest: "$2a$10$E
zc7Ncysvk17BoH.v/aOs.3Jmcu1ZdWVd0GnKQZiE/cy...">, #<Student id: 5, name: "Kevin", nickname: "Rockwood", email: "kevin@rockwood.me", image_url: "", password_digest: "$2a$10$UTKQY0qQPd9EpjnA8M67we
Uog0VCQpNHxOVe8UQpBpWm...">]>`

**Comment by jaimerump** [comment]
It looks like it's getting the corresponding student record for every single attendance that isn't the given date, so if you attended 2 classes previously, you show up twice because you have 2 attendances that aren't the given date. 

@Sparkesg1 was the one who originally had issues with the absent method they gave us, and he posted his working version in issue #68.

**Comment by mitchlloyd** [comment]
It looks like the query shown in the assignment had two problems:

1) It doesn't show students as absent if they have never recorded an attendance.
2) There is a joining issue that can return duplicates of students.  One way to handle this issue is to add ".distinct" to the end of the query.

You can take a look at the way [this query is implemented our version of the application](https://github.com/gaslight/nku-rails/blob/master/app/models/student.rb). I don't think this implementation has the issues above.  However, when I get some time I want to expand the automated tests around this query to catch the issues with the query shown in the assignment.

**Comment by mitchlloyd** [comment]
@camdixon Do you have any luck when updating the queries to the ones I linked to?

**Comment by Spartan-196** [comment]
I was having the same issue of no one showed up as absent until they were present at least once. I will try out the new queries.
