### ISSUE TITLE
Can't Use Partial Dates

### ISSUE THREAD

**Issue by jaimerump** [launchscout/nku#96]
I just found out that Rails doesn't support partial dates, eg: "2012-03-00". This is a problem for me because a lot of the dates I work with have unknown parts. A lot of the solutions I've found don't support sorting, which I will also need, or are for Rails 2. 

Does anyone know of a good Rails 4 compatible solution that allows both incomplete dates and sorting?

**Comment by camdixon** [comment]
Possibly, 

but which part of the dates are not complete?  (e.g. Month, day, Month & day)?
I'm confused as to why they are incomplete.  Is it because you need something to reoccur every so often, or that something is being produced at a date in the future not yet known?

You could try an array / hash that has a range of dates you specify, if it's not clear which one you will need.  For example, a particular day in a week I will need to find all the days in the week

```
@weekStart = @viewDate.beginning_of_week(start_day = :monday)
 @days_from_this_week = (@viewDate.at_beginning_of_week..@viewDate.at_end_of_week).map
```

http://stackoverflow.com/questions/18199705/ruby-on-rails-how-to-get-the-current-week-and-loop-through-it-to-display-its-da

With this potential solution, you might not be able to call .sort on it.  What it would allow you to do I believe is specify the sorted order yourself.

**Comment by alexkoepke** [comment]
If you are trying to import data I would write a script that would parse the data and change it to the desired format.

An excell macro that saves your file as a .csv might be a good option.
—
Alex Koepke
(513) 236-7281

**Comment by jaimerump** [comment]
The column that this would be an issue for is release dates for items. Some items, like games, are released on a specific date and Rails can handle these. Some don't have a specific day, like older toys, so those would only have a month and year, or sometimes only an older year. These are the ones I'm having trouble with, since Rails by default only supports a complete date or nil.

So for some dates I have Y-m-d, some I only have Y-m or just Y, and some I have nothing at all. I need something that can allow all of these formats AND allow sorting by dates, however it stores them. 

I've tried going in and manually setting the columns like `@item.release_date = "2012-03-00"`, but when I save the item, Rails converts that back to nil. Storing the dates as string makes sorting and formatting much slower and more difficult, as would storing them as separate columns.

**Comment by jaimerump** [comment]
I've been looking for 2 days now and haven't been able to find a good gem for this that doesn't completely mangle the data format. I think I'll stick with a date object so I get all of its benefits with sorting and formatting, but plug in 01 for a missing day or month so the class doesn't explode on the cast. I can do something similar to [this answer](http://stackoverflow.com/a/22895877/1461038) and set a flag for the completeness of the date, so I have a way to tell between a genuine 01 and a placeholder for a blank.
